//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderId { get; set; }
        public string ordersInvoiceNo { get; set; }
        public string Rsize { get; set; }
        public string Gsm { get; set; }
        public string Colour { get; set; }
        public string NetWt { get; set; }
        public string Type { get; set; }
        public string BagSize { get; set; }
        public string RollStatus { get; set; }
        public System.DateTime Date { get; set; }
        public string Remarks { get; set; }
        public string PartyName { get; set; }
        public string PLNo { get; set; }
        public string DCNo { get; set; }
    }
}
