//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingList
    {
        public int Id { get; set; }
        public Nullable<int> S_No { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> Roll_No { get; set; }
        public string Colour { get; set; }
        public string Gsm { get; set; }
        public string Width { get; set; }
        public string RollStatus { get; set; }
        public Nullable<decimal> NetWt { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> JobWorkId { get; set; }
    
        public virtual JobWork JobWork { get; set; }
    }
}
